export enum Platform {
  META = 'META',
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  X = 'X',
  LINKEDIN = 'LINKEDIN',
}

export enum PostStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}

export enum ScheduleJobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SCHEDULED = 'SCHEDULED',
  RETRYING = 'RETRYING',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}